apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 name: routers.mydatacenter.com
spec:
 group: mydatacenter.com
 versions:
 - name: v1
   served: true
   storage: true
   schema:
    openAPIV3Schema:
     type: object
     properties:
      spec:
       type: object
       properties:
        dataCenter:
         type: string
        rack:
         type: integer
        type:
         type: string
        firmWare:
         type: string
 scope: Cluster
 names:
      plural: routers
      singular: router
      kind: Router
      shortNames:
      - rts





