apiVersion: apps/v1
kind: Deployment
metadata:
 name: autoscale
 namespace: test
spec:
 replicas: 2
 selector:
  matchLabels:
   app: test
 template:
  metadata:
   labels:
    app: test
  spec:
   containers:
    - name: webtest
      image: nginx
      ports:
       - containerPort: 80
      resources:
       requests:
        cpu: 200m
        memory: "256Mi"

