apiVersion: v1
kind: ResourceQuota
metadata:
 name: rquota
 namespace: test
spec:
 hard:
  cpu: "12"
  memory: "8Gi"

#hard:
#  requests.cpu: "2"
#  requests.memory: 2Gi
#  limits.cpu: "4"
#  limits.memory: 4Gi

