---
apiVersion: apps/v1
kind: Deployment
metadata:
 namespace: test
 name: pvdeploy
spec:
 replicas: 3
 selector:
  matchLabels:
   env: test
 template:
  metadata:
   labels:
    env: test
  spec:
   containers:
    - name: dbcon
      image: mariadb:10.4
      ports:
       - containerPort: 3306
      env:
       - name: MARIADB_ROOT_PASSWORD
         valueFrom:
          secretKeyRef:
           name: sectest
           key: MARIADB_ROOT_PASSWORD
      volumeMounts:
       - name: testvol
         mountPath: "/tmp/abc"
         readOnly: yes
       - name: pvclaimvol
         mountPath: "/mnt/data"
   volumes:
    - name: testvol
      secret: 
       secretName: sectest
    - name: pvclaimvol
      persistentVolumeClaim:
       claimName: dev-pvclaim
