apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: sepagent
    namespace: dset
spec:
    selector:
        matchLabels:
            env: dev
    template:
        metadata:
            labels:
                env: dev
        spec:
            containers:
                - name: dset-dev
                  image: nginx
                  ports:
                    - containerPort: 80
