apiVersion: apps/v1
kind: Deployment
metadata:
  name: uatab
  namespace: uat
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
       nodeaffinity:
        requiredDuringSchedulingIgnoreDuringExecution:
         nodeSelectorTerms:
          - matchExpressions:
            - key: gpu
              operator: In
              values:
               - nvidia
      containers:
      - name: webconf
        image: nginx
        ports:
        - containerPort: 80

              
      
