apiVersion: apps/v1
kind: Deployment
metadata:
 name: johndev
 namespace: finance
 labels:
  app: web
spec:
 replicas: 3
 selector:
  matchLabels:
   app: web
 template:
  metadata:
   labels:
    app: web
  spec:
   containers:
    - name: webcon
      image: nginx
      ports:
       - containerPort: 80
