---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: init-deploy
 namespace: uat
spec:
 replicas: 1
 selector:
  matchLabels:
   env: dev
 template:
  metadata:
   labels:
    env: dev
  spec:
   volumes:
    - name: shared-volume
      emptyDir: {}
   initContainers:
    - name: initcon
      image: busybox
      volumeMounts:
       - name: shared-volume
         mountPath: /testing
      command: ['/bin/sh']
      args: ["-c","echo '<h1>WELCOME TO DEVOS</h1>' > /testing/index.html"]
   containers:
    - name: nginxcon
      image: nginx
      volumeMounts:
       - name: shared-volume
         mountPath: /usr/share/nginx/html
      ports:
       - containerPort: 80

    
