apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: test
  labels:
    app: tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: gpu
                operator: In
                values:
                - nvidia
            topologyKey: "kubernetes.io/hostname"   
      containers:
      - name: tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 80


