apiVersion: v1
kind: Service
metadata:
 name: init-service
 namespace: uat
spec:
 selector:
   env: dev
 ports:
  - name: initport
    port: 80
    protocol: TCP
    targetPort: 80
 type: LoadBalancer
  
