apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-prefer
  namespace: test
spec:
  selector:
    matchLabels:
      app: store
  replicas: 3
  template:
    metadata:
      labels:
        app: store
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 100
             podAffinityTerm:
              labelSelector:
               matchExpressions:
               - key: app
                 operator: In
                 values:
                 - store
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis-server
        image: redis:3.2-alpine
