apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginxdep
 namespace: test
spec:
 replicas: 3
 selector:
  matchLabels:
   env: dev
 template:
  metadata:
   labels:
    env: dev
  spec:
   containers:
    - name: nginx-web01
      image: nginx:1.17
      ports:
       - containerPort: 80
      livenessProbe:
       exec:
        command:
         - ls
         - /usr/share/nginx/html/index.html
       initialDelaySeconds: 5
       periodSeconds: 5
       timeoutSeconds: 1
       failureThreshold: 1
