apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginxdep
 namespace: test
spec:
 replicas: 2
 selector:
  matchLabels:
   env: dev
 template:
  metadata:
   labels:
    env: dev
  spec:
   containers:
    - name: nginx-web01
      image: nginx:1.17
      ports:
       - containerPort: 80
#      livenessProbe:
#       httpGet:
#        path: /
#        port: 80
#       initialDelaySeconds: 10
#       periodSeconds: 10
#       timeoutSeconds: 1
#       failureThreshold: 1
      lifecycle:
       postStart:
        exec:
         command: ["/bin/bash", "-c", "rm -rf /usr/share/nginx/html/index.html"]
      readinessProbe:
       httpGet:
        path: /
        port: 80
       initialDelaySeconds: 5
       periodSeconds: 5
       failureThreshold: 15
       successThreshold: 1

